name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            ref: ${{ github.event.pull_request.head.sha || github.ref }}
        - name: Set up JDK 8
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
            cache: "maven"
        - name: Build with Maven
          run: mvn -B clean package

        - name: Archive artifact
          uses: actions/upload-artifact@v4
          with:
            name: liquibase-license-checker-artifacts
            path: |
              target/*.jar
            

